kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: portal-soap
spec:
  # path: /portal_soap
  to:
    kind: Service
    name: portal_soap
    weight: 100
  port:
    targetPort: lwfw
  wildcardPolicy: None