kind: Service
apiVersion: v1
metadata:
  name: portal-soap
spec:
  ports:
    - name: lwfw
      protocol: TCP
      port: 30008
      targetPort: lw-adapter
  selector:
    app.kubernetes.io/component: asi-server
  type: ClusterIP