kind: Service
apiVersion: v1
metadata:
  name: portal-soap
spec:
  ports:
    - name: lwfw
      protocol: TCP
      port: 10580
      targetPort: 10580
  selector:
    app.kubernetes.io/component: asi-server
  type: ClusterIP